## Indexing and Slicing: Part A

In [2]:
import numpy as np

In [4]:
array_1d = np.array([1, 2, 3, 4, 5, 6])

In [6]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [8]:
array_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [10]:
array_1d[0]

1

In [12]:
array_1d[1]

2

In [14]:
array_1d[-3]

4

In [16]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
array_2d[0, 1]

2

In [20]:
array_2d[0, 1]

2

In [22]:
array_2d[1, -1]

6

In [24]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
array_3d[0, 1, 2]

6

In [28]:
array_3d[1, 1, -1]

12

## Slicing the array

In [31]:
array_1d

array([1, 2, 3, 4, 5, 6])

In [33]:
array_1d[1:]

array([2, 3, 4, 5, 6])

In [35]:
array_1d[3:5]

array([4, 5])

In [37]:
array_1d[-3:-1]

array([4, 5])

In [39]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
array_2d[1, 1:]

array([5, 6])

In [43]:
array_2d[-2:-3:-1]

array([[1, 2, 3]])

In [45]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
array_3d[0, 1:, 1:]

array([[5, 6]])