### Arithmetic Operation with numpy

In [2]:
import numpy as np

In [4]:
A = np.array([
    [1, 2, 1], 
    [2, 2, 3]
])
B = np.array([3, 4, 5])

In [6]:
A

array([[1, 2, 1],
       [2, 2, 3]])

In [8]:
B

array([3, 4, 5])

In [10]:
# Add two Array
np.add(A, B)

array([[4, 6, 6],
       [5, 6, 8]])

In [12]:
# Subtract
np.subtract(B, A)

array([[2, 2, 4],
       [1, 2, 2]])

In [14]:
# Multipy
np.multiply(A, B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [16]:
# Divide
np.divide(A, B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

In [18]:
# Power of array element
np.power(A, 2)

array([[1, 4, 1],
       [4, 4, 9]], dtype=int32)

In [20]:
np.power(A, B)

array([[  1,  16,   1],
       [  8,  16, 243]])