In [1]:
import numpy as np

In [3]:
numpy_arr = np.array([x for x in range(1, 10)])

In [5]:
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
numpy_arr.reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
numpy_arr = np.array([x for x in range(1, 13)])

In [11]:
numpy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
# convert in 3D array
numpy_arr.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
# reshape the array
numpy_arr.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [19]:
numpy_arr.reshape(3, 2, 3)  # Error: size of the array is 12 not 18

ValueError: cannot reshape array of size 12 into shape (3,2,3)

In [23]:
numpy_arr.reshape(2, 2, -1)  # -1 will automatically calculate last
# of the array, it is useful when we are using dynamic dataset

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
numpy_arr = numpy_arr.reshape(3, 2, 2)


In [27]:
numpy_arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [31]:
# it will convert in 1D array
numpy_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])