In [1]:
import numpy as np

In [3]:
np.array(24)

array(24)

In [5]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [7]:
# 2D array
np.array([
    [1, 2, 3],
    [4, 5, 6]
])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# 3D array
np.array([
    [
        [1, 2, 3],
        [2, 3, 4]
    ],
    [
        [5, 5, 5],
        [6, 6, 6]
    ]
])

array([[[1, 2, 3],
        [2, 3, 4]],

       [[5, 5, 5],
        [6, 6, 6]]])

In [11]:
numpy_arr = np.array([
    [
        [1, 2, 3],
        [2, 3, 4]
    ],
    [
        [5, 5, 5],
        [6, 6, 6]
    ]
])

In [13]:
numpy_arr.shape

(2, 2, 3)

In [15]:
# number of dimention
numpy_arr.ndim


3