## ufunc  Examples


In [1]:
import numpy as np


In [2]:
# Numbers for which square root will be calculated
np_sqrt = np.sqrt([2, 4, 9, 16])


In [3]:
np_sqrt


array([1.41421356, 2.        , 3.        , 4.        ])

In [4]:
from numpy import pi

np.cos(0)


1.0

In [5]:
np.sin(pi/2)


1.0

In [6]:
np.cos(pi)


-1.0

In [7]:
# Return the floor of the input element wise
np.floor([1.5, 1.6, 2.7, 3.3, 1.1, -0.3, -1.4])


array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [8]:
# Exponential function for complex mathematical calculations
np.exp([0, 1, 5])


array([  1.        ,   2.71828183, 148.4131591 ])

## Shap Manipulation - Example
You can use certain function to manipulate the shape of an array to do the following:

In [9]:
new_cyclist_trials = np.array([
    [10, 15, 17, 26, 13, 19],
    [12, 11, 21, 24, 14, 23]
])


In [10]:
new_cyclist_trials.ravel()


array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [11]:
new_cyclist_trials.reshape(3, 4)


array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [12]:
new_cyclist_trials.resize(2, 6)


In [13]:
new_cyclist_trials


array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [14]:
np.hsplit(new_cyclist_trials, 2)


[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

In [15]:
new_cyclist_1 = np.array([10, 15, 17, 26, 13, 19])


In [16]:
new_cyclist_2 = np.array([12, 11, 21, 24, 14, 23])


In [17]:
np.hstack((new_cyclist_1, new_cyclist_2))


array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])