## Problem Statement

Create a one-dimension array with alias as np and perform the following methods:

1. np.zeros()
2. np.ones()
3. np.empty()
4. np.arange()
5. np.reshape()
6. np.linspace()

In [4]:
# import NumPy library
import numpy as np


In [5]:
# first NumPy array
first_numpy_array = np.array([1, 2, 3, 4])

# Regular array: Mention array elements within brackets


In [6]:
print(first_numpy_array)


[1 2 3 4]


In [7]:
# array with zeros
# Zeros array: Mention shape of array within parentheses
array_with_zeros = np.zeros((3, 3))
array_with_zeros


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Array with ones
array_with_ones = np.ones((3, 3))
array_with_ones


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# array with empty
array_with_empty = np.empty((2, 3))
array_with_empty


array([[1.02049460e-311, 1.02049459e-311, 1.02049460e-311],
       [1.02049460e-311, 1.02049460e-311, 1.02049460e-311]])

In [11]:
# array with arange method
np_arange = np.arange(12)

In [13]:
# print array
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
# reshape method to change / create array
np_arange.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
# linspace for linearly (equal) spaced data elements
np_linspce = np.linspace(1, 6, 5)

# First element = 1
# Last element = 6
# Total number of equidistant elements = 5

In [21]:
# print linespaced array
print(np_linspce)

[1.   2.25 3.5  4.75 6.  ]


In [35]:
# One dimensional array
oneD_array = np.arange(15)

In [37]:
# print 1D array
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [39]:
# Two dimensional array
TwoD_array = oneD_array.reshape(3, 5)

In [41]:
# print 2D array
print(TwoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [43]:
# Three dimensional array
ThreeD_array = np.arange(27).reshape(3, 3, 3)

In [45]:
# Print 3D array
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
